CREATE TABLE tb_categoria (
ID BIGINT AUTO_INCREMENT PRIMARY KEY,
NOME_CATEGORIA VARCHAR(150) NOT NULL,
TECNOLOGIA VARCHAR(50) NOT NULL);

CREATE TABLE tb_starter (
ID BIGINT AUTO_INCREMENT PRIMARY KEY,
NOME VARCHAR(150) NOT NULL,
CPF VARCHAR(20) NOT NULL,
QUATRO_LETRAS VARCHAR(4) NOT NULL,
EMAIL VARCHAR(100) NOT NULL,
CATEGORIA_ID BIGINT NOT NULL,
FOREIGN KEY (CATEGORIA_ID) REFERENCES tb_categoria(ID));